//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blueapp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("blueapp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   애플리케이션 시작됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string application_started {
            get {
                return ResourceManager.GetString("application_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   애플리케이션 정지됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string application_stopped {
            get {
                return ResourceManager.GetString("application_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   앱 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자동 로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string auto_login {
            get {
                return ResourceManager.GetString("auto_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string check {
            get {
                return ResourceManager.GetString("check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   개수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다크모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string darkmode {
            get {
                return ResourceManager.GetString("darkmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터베이스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string db {
            get {
                return ResourceManager.GetString("db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원탈퇴과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string delete_id {
            get {
                return ResourceManager.GetString("delete_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0에서 100 사이의 정수를 입력하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string enter_0_to_100 {
            get {
                return ResourceManager.GetString("enter_0_to_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프레임워크과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string framework {
            get {
                return ResourceManager.GetString("framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   돌아가기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string go_back {
            get {
                return ResourceManager.GetString("go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사진과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   재고 관리 페이지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string inventory_management_page {
            get {
                return ResourceManager.GetString("inventory_management_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   언어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로딩중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그아웃과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품을 추가하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_addproduct_confirm {
            get {
                return ResourceManager.GetString("msg_addproduct_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호를 변경하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_changepw_confirm {
            get {
                return ResourceManager.GetString("msg_changepw_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디를 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_deleteid_confirm {
            get {
                return ResourceManager.GetString("msg_deleteid_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string password_new {
            get {
                return ResourceManager.GetString("password_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로운 비밀번호 확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string password_new_check {
            get {
                return ResourceManager.GetString("password_new_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이전 비밀번호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string password_old {
            get {
                return ResourceManager.GetString("password_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string product_add {
            get {
                return ResourceManager.GetString("product_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제품 이름과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string production_date {
            get {
                return ResourceManager.GetString("production_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산 관리 페이지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string production_management_page {
            get {
                return ResourceManager.GetString("production_management_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산 시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string production_start {
            get {
                return ResourceManager.GetString("production_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생산 정지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string production_stop {
            get {
                return ResourceManager.GetString("production_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   패스워드가 일치하지 않습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pw_not_match {
            get {
                return ResourceManager.GetString("pw_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   품질 관리 페이지과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string quality_management_page {
            get {
                return ResourceManager.GetString("quality_management_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수량과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   평가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회원가입과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아이디 저장과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string save_id {
            get {
                return ResourceManager.GetString("save_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   텍스트가 비어있음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string text_is_empty {
            get {
                return ResourceManager.GetString("text_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업데이트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
